### ISSUE TITLE
New error after updating Nim: internal error: environment misses: x

### ISSUE THREAD

**Issue by MortimerSnerd** [nim-lang/Nim#11214]
After updating to the latest devel branch this morning (532edc3e9a9e5bd4ad8780aad304cef6932213ed), some macro code stopped compiling with the this error message: "Error: internal error: environment misses: x".   I bisected to the commit that seems to introduce the error, 2475d92c36e26e44372175c2cf4c21fbab084619 "fixes #10192".

On the downside, I haven't been able to reduce the code down to a reproducible test case yet.  The code it's complaining about is a quoted section inside of a macro function that's being added to a nnkStmtList,:

```nim
  let bang = newTree(nnkAccQuoted, newIdentNode("!"))
  result.add(quote do:
             template `bang`*(idx: `rowtype`) : `rowtype` = 
               let x = idx # ERROR points to x in this line
               assert int(x) >= 0, "Bad row returned from forced operation."
               x)  
```

And the full stack trace from the internal error is:
```
Traceback (most recent call last)
nim.nim(98)              nim
nim.nim(75)              handleCmdLine
cmdlinehelper.nim(92)    loadConfigsAndRunMainCommand
main.nim(198)            mainCommand
main.nim(90)             commandCompileToC
modules.nim(147)         compileProject
modules.nim(88)          compileModule
passes.nim(203)          processModule
passes.nim(86)           processTopLevelStmt
sem.nim(603)             myProcess
sem.nim(571)             semStmtAndGenerateGenerics
semstmts.nim(2160)       semStmt
semexprs.nim(943)        semExprNoType
semexprs.nim(2696)       semExpr
importer.nim(212)        evalImport
importer.nim(182)        impMod
importer.nim(154)        myImportModule
modules.nim(102)         importModule
modules.nim(88)          compileModule
passes.nim(197)          processModule
passes.nim(86)           processTopLevelStmt
cgen.nim(1874)           myProcess
ccgstmts.nim(1258)       genStmts
ccgexprs.nim(2631)       expr
ccgexprs.nim(2408)       genStmtList
ccgstmts.nim(1258)       genStmts
ccgexprs.nim(2653)       expr
ccgstmts.nim(388)        genVarStmt
ccgstmts.nim(368)        genSingleVar
ccgstmts.nim(140)        loadInto
ccgexprs.nim(2613)       expr
(32 calls omitted) ...
ccgstmts.nim(1258)       genStmts
ccgexprs.nim(2661)       expr
ccgstmts.nim(1248)       genAsgn
ccgstmts.nim(130)        loadInto
ccgcalls.nim(568)        genAsgnCall
ccgcalls.nim(195)        genPrefixCall
cgen.nim(589)            initLocExpr
ccgexprs.nim(2534)       expr
cgen.nim(1172)           genProc
cgen.nim(1137)           genProcNoForward
cgen.nim(1012)           genProcAux
ccgstmts.nim(1258)       genStmts
ccgexprs.nim(2631)       expr
ccgexprs.nim(2408)       genStmtList
ccgstmts.nim(1258)       genStmts
ccgexprs.nim(2632)       expr
ccgstmts.nim(426)        genIf
ccgexprs.nim(2631)       expr
ccgexprs.nim(2419)       genStmtList
ccgstmts.nim(1258)       genStmts
ccgexprs.nim(2657)       expr
ccgstmts.nim(445)        genReturnStmt
ccgstmts.nim(1258)       genStmts
ccgexprs.nim(2661)       expr
ccgstmts.nim(1248)       genAsgn
ccgstmts.nim(130)        loadInto
ccgcalls.nim(568)        genAsgnCall
ccgcalls.nim(195)        genPrefixCall
cgen.nim(589)            initLocExpr
ccgexprs.nim(2534)       expr
cgen.nim(1172)           genProc
cgen.nim(1137)           genProcNoForward
cgen.nim(1012)           genProcAux
ccgstmts.nim(1258)       genStmts
ccgexprs.nim(2631)       expr
ccgexprs.nim(2408)       genStmtList
ccgstmts.nim(1258)       genStmts
ccgexprs.nim(2629)       expr
ccgstmts.nim(610)        genBlock
ccgexprs.nim(2631)       expr
ccgexprs.nim(2419)       genStmtList
ccgstmts.nim(1258)       genStmts
ccgexprs.nim(2631)       expr
ccgexprs.nim(2408)       genStmtList
ccgstmts.nim(1258)       genStmts
ccgexprs.nim(2631)       expr
ccgexprs.nim(2419)       genStmtList
ccgstmts.nim(1258)       genStmts
ccgexprs.nim(2629)       expr
ccgstmts.nim(610)        genBlock
ccgexprs.nim(2631)       expr
ccgexprs.nim(2408)       genStmtList
ccgstmts.nim(1258)       genStmts
ccgexprs.nim(2653)       expr
ccgstmts.nim(388)        genVarStmt
ccgstmts.nim(340)        genSingleVar
cgen.nim(602)            initLocExprSingleUse
ccgexprs.nim(2601)       expr
ccgcalls.nim(557)        genCall
ccgcalls.nim(195)        genPrefixCall
cgen.nim(589)            initLocExpr
ccgexprs.nim(2534)       expr
cgen.nim(1172)           genProc
cgen.nim(1137)           genProcNoForward
cgen.nim(1012)           genProcAux
ccgstmts.nim(1258)       genStmts
ccgexprs.nim(2631)       expr
ccgexprs.nim(2408)       genStmtList
ccgstmts.nim(1258)       genStmts
ccgexprs.nim(2661)       expr
ccgstmts.nim(1248)       genAsgn
ccgstmts.nim(140)        loadInto
ccgexprs.nim(2621)       expr
ccgexprs.nim(1419)       genObjConstr
ccgexprs.nim(2601)       expr
ccgcalls.nim(557)        genCall
ccgcalls.nim(195)        genPrefixCall
cgen.nim(589)            initLocExpr
ccgexprs.nim(2534)       expr
cgen.nim(1172)           genProc
cgen.nim(1137)           genProcNoForward
cgen.nim(970)            genProcAux
transf.nim(1121)         transformBody
lambdalifting.nim(813)   liftLambdas
lambdalifting.nim(734)   liftCapturedVars
lambdalifting.nim(734)   liftCapturedVars
lambdalifting.nim(734)   liftCapturedVars
lambdalifting.nim(734)   liftCapturedVars
lambdalifting.nim(734)   liftCapturedVars
lambdalifting.nim(734)   liftCapturedVars
lambdalifting.nim(687)   liftCapturedVars
lambdalifting.nim(516)   accessViaEnvParam
msgs.nim(533)            localError
msgs.nim(515)            liMessage
msgs.nim(346)            handleError
msgs.nim(331)            quit
```

I have to break away from it for now, but I'll get back to getting something reproducible in the evening.

### Additional Information

```
$ nim -v
Nim Compiler Version 0.19.9 [Windows: amd64]
Compiled at 2019-05-09
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 532edc3e9a9e5bd4ad8780aad304cef6932213ed
active boot switches:
```

**Comment by narimiran** [comment]
> I'll get back to getting something reproducible in the evening.

ping :)

**Comment by MortimerSnerd** [comment]
Sorry, crazy week. Needless to say, I couldn't reduce it down to something I can hand in as test case.  I need to restructure that macro anyway for other reasons, so I'm curious to see if anything falls out of that.

But it will take me a bit to get back to it.  If you need to close this down, or put it in some dusty corner pending a test case, not a problem with me.

**Comment by Araq** [comment]
Ok. We will change how ``.gensym`` is implemented anyway.

**Comment by konradmb** [comment]
I think this issue is related to: https://github.com/flyx/emerald/issues/20

I've done a git bisection and it showed this commit: https://github.com/nim-lang/Nim/commit/eaca5be9d6e205e8aa7055306122a6c053ef35a6
Then I've bisected that pull request and first commit exhibiting this issue is: https://github.com/nim-lang/Nim/pull/8489/commits/532bcc753fd8c94d67ec4fa31bc81d35ba703a6d
I don't know if you can trust this, because a lot of commits were skipped and earlier commits were giving SIGSEGV, so that's a first commit showing the "environment misses" error.

**Comment by pgkos** [comment]
Example:
```nim
import macros

macro foo*(param: untyped): untyped =
  let
    sym1 = genSym(nskVar)
    sym2 = sym1

    proc1 = genSym(nskProc)
    proc2 = genSym(nskProc)

  result = quote do:
    proc `proc1` =
      var `sym1`: int

    proc `proc2` =
      var `sym2`: int

    let `param` = (`proc1`, `proc2`)

foo(bar)
```

**Comment by konradmb** [comment]
I've done a bisection based on @pgkos example:
```
git bisect start
# bad: [e7471cebae2a404f3e4239f199f5a0c422484aac] koch.nim: hotfix for nightly builds
git bisect bad e7471cebae2a404f3e4239f199f5a0c422484aac
# good: [c6f601d48ec81e0d6e052ba0d19a195b55cc68f2] bump version to 0.19.6
git bisect good c6f601d48ec81e0d6e052ba0d19a195b55cc68f2
# good: [66c0f7c3fb214485ca6cfd799af6e50798fcdf6d] development version is 0.19.1
git bisect good 66c0f7c3fb214485ca6cfd799af6e50798fcdf6d
# bad: [9985706fb812156fa6f805989063293ca71599df] GC tests: make them take less time to save CI cycles
git bisect bad 9985706fb812156fa6f805989063293ca71599df
# good: [d21529649746e68fd6f3f955627eda3ee0017534] Merge pull request #9846 from timotheecour/pr_getpid
git bisect good d21529649746e68fd6f3f955627eda3ee0017534
# bad: [7b9ba71b47efb5fa0a3d4ea852bf11c57ca0be04] Update osproc.nim
git bisect bad 7b9ba71b47efb5fa0a3d4ea852bf11c57ca0be04
# bad: [d20a27321524a08fba1831176e607b837f64ae7f] Merge pull request #9917 from timotheecour/pr_dump_msg
git bisect bad d20a27321524a08fba1831176e607b837f64ae7f
# bad: [cd81f368d184dae6268ccf5f4bdc771a661f4ac1] Merge pull request #9826 from cooldome/destructor_move_them_all
git bisect bad cd81f368d184dae6268ccf5f4bdc771a661f4ac1
# bad: [606b43ba1130b5672e91ddd156d81267634ed465] Merge pull request #9911 from nc-x/fixes-#9627
git bisect bad 606b43ba1130b5672e91ddd156d81267634ed465
# good: [f838b1e6c14c8c505eea6e2107295f166c67f346] fix #9872: setLen now works properly at CT [backport]
git bisect good f838b1e6c14c8c505eea6e2107295f166c67f346
# bad: [c16963083d828b7920c221a5031b509c9824db4a] Merge pull request #9912 from nim-lang/araq-fixes-nested-gensym
git bisect bad c16963083d828b7920c221a5031b509c9824db4a
# good: [e03fb08c24b33a6e25d61da93ae07bd08c9ae648] change approach
git bisect good e03fb08c24b33a6e25d61da93ae07bd08c9ae648
# good: [8035f408f1323ba81c8db794ad58687bace78afa] Merge pull request #9898 from cooldome/enum_notused
git bisect good 8035f408f1323ba81c8db794ad58687bace78afa
# bad: [e8747059710370819800bdc0742fa86761c6737b] fixes nested gensym'ed parameters; fixes #9476
git bisect bad e8747059710370819800bdc0742fa86761c6737b
# first bad commit: [e8747059710370819800bdc0742fa86761c6737b] fixes nested gensym'ed parameters; fixes #9476
```
Setting this line to `true` fixes it, but I don't know what I'm doing :smile: 
https://github.com/nim-lang/Nim/blob/e8747059710370819800bdc0742fa86761c6737b/compiler/sem.nim#L210

**Comment by narimiran** [comment]
> `first bad commit: [e8747059710370819800bdc0742fa86761c6737b] fixes nested gensym'ed parameters; fixes #9476`

This is the same commit that is mentioned in #11494 as a root cause too.

**Comment by Araq** [comment]
```nim

import macros

macro foo*(param: untyped): untyped =
  let
    sym1 = genSym(nskVar)
    sym2 = sym1

    proc1 = genSym(nskProc)
    proc2 = genSym(nskProc)

  result = quote do:
    proc `proc1` =
      var `sym1`: int

    proc `proc2` =
      var `sym2`: int

    let `param` = (`proc1`, `proc2`)

foo(bar)
```

is simply invalid code, you cannot re-use gensym'ed symbols like that. The only problem with it is the error message. 

I believe the original bug has been fixed, so closing.

**Comment by bluenote10** [comment]
Intuitively the code makes sense. Is the problem that e.g. `proc1` is used both for the proc definition and as a value? What is the correct way to achieve that?

**Comment by Araq** [comment]
No, "intuitively" it's wrong, look at

```nim
  let
    sym1 = genSym(nskVar)
    sym2 = sym1 # er, what?
```

**Comment by bluenote10** [comment]
It is not possible to have two variables `sym1` and `sym2` refer to the same symbol?
```nim
let
  sym1 = genSym(nskLet)
  sym2 = sym1

result = quote do:
  let `sym1` = "hello world"
  echo `sym1`
  echo `sym2`
```
produces AST
```
let :tmp_186047 = "hello world"
echo :tmp_186047
echo :tmp_186047
```
and seems to work.

**Comment by konradmb** [comment]
Regression with emerald still persists on devel. Should i open a new issue?

**Comment by Araq** [comment]
>  Should i open a new issue?

Yes, but please this time with some code snippet that reproduces the problem. And if it's wrong ``gensym`` usage, please fix the code instead.
