### ISSUE TITLE
Compiled binary includes full path to internal nim files

### ISSUE THREAD

**Issue by daniel-j** [nim-lang/Nim#11572]
Compiling any program causes a long filesystem path outside my project to be included in the final binary. I have tried the following flags and it still gets included:
`-d:release --listFullPaths:off --excessiveStackTrace:off --opt:size`

### Example

```nim
echo "Hello World!"
```
`$ nim c -d:release --listFullPaths:off --excessiveStackTrace:off --opt:size helloworld.nim`

### Current Output

```
$ strings helloworld | grep toolchains
../../../home/djazz/.choosenim/toolchains/nim-0.20.0/lib/system/fatal.nim
```

### Expected Output

(empty)

### Additional Information
* Nim version 0.20.0 (e7471cebae2a404f3e4239f199f5a0c422484aac) installed with choosenim
* Operating System: Arch Linux
* [This line in fatal.nim](https://github.com/nim-lang/Nim/blob/436f57065197bee86c9539b75de3a73e5bda3f10/lib/system/fatal.nim#L39) seems related to the issue (someone on irc pointed out).
* irc log: https://irclogs.nim-lang.org/24-06-2019.html#17:04:10

**Comment by dizzyliam** [comment]
Does this result in unexpected behavior if the linked files are no longer available?

**Comment by daniel-j** [comment]
No, it's probably just for debugging. I just don't want my username etc to be included in the final binary.

**Comment by dizzyliam** [comment]
Does it do the same thing when you compile with the release flag? If not, then that should be an easy feature/patch to implement.

**Comment by dizzyliam** [comment]
Sorry, I misread your issue. I'll have a look when I next can. Exited to start contributing!

**Comment by daniel-j** [comment]
Yes, as I stated in the issue, those flags does not remove it.

**Comment by dizzyliam** [comment]
Is anyone able to test this on a not arch-based distro?

**Comment by dom96** [comment]
I doubt this is arch-specific. Yeah, we need a way to prevent these paths making their way into the binary.

**Comment by dom96** [comment]
This should indeed be a fairly easy PR, probably just need to check one of these flags in a specific place. If ``fatal.nim`` is the only filename making its way in there then it might be even easier.

**Comment by dizzyliam** [comment]
I'm looking at the code in compiler/msgs.nim that is responsible for checking the flags and deciding what file path to use. Maybe it is an edgecase in the lines that process the full path? I'll be freed up in about an hour, so I'll start troubleshooting then.

**Comment by daniel-j** [comment]
On the project I'm working on I get this in debug:
```
/home/djazz/.choosenim/toolchains/nim-0.20.0/lib/system/io.nim
/home/djazz/.choosenim/toolchains/nim-0.20.0/lib/system/iterators.nim
/home/djazz/.choosenim/toolchains/nim-0.20.0/lib/system/alloc.nim
/home/djazz/.choosenim/toolchains/nim-0.20.0/lib/system/gc_common.nim
/home/djazz/.choosenim/toolchains/nim-0.20.0/lib/system/avltree.nim
/home/djazz/.choosenim/toolchains/nim-0.20.0/lib/system/gc.nim
/home/djazz/.choosenim/toolchains/nim-0.20.0/lib/system/osalloc.nim
/home/djazz/.choosenim/toolchains/nim-0.20.0/lib/system/mmdisp.nim
/home/djazz/.choosenim/toolchains/nim-0.20.0/lib/system/cellsets.nim
/home/djazz/.choosenim/toolchains/nim-0.20.0/lib/system.nim
/home/djazz/.choosenim/toolchains/nim-0.20.0/lib/system/strmantle.nim
/home/djazz/.choosenim/toolchains/nim-0.20.0/lib/system/fatal.nim
```
If I add -d:release I get the following:
```
/home/djazz/.choosenim/toolchains/nim-0.20.0/lib/system/fatal.nim
```

--listFullPaths:off turns some of the paths into relative (debug):
```
/home/djazz/.choosenim/toolchains/nim-0.20.0/lib/system/io.nim
/home/djazz/.choosenim/toolchains/nim-0.20.0/lib/system/iterators.nim
/home/djazz/.choosenim/toolchains/nim-0.20.0/lib/system/alloc.nim
/home/djazz/.choosenim/toolchains/nim-0.20.0/lib/system/gc_common.nim
/home/djazz/.choosenim/toolchains/nim-0.20.0/lib/system/avltree.nim
/home/djazz/.choosenim/toolchains/nim-0.20.0/lib/system/gc.nim
/home/djazz/.choosenim/toolchains/nim-0.20.0/lib/system/osalloc.nim
/home/djazz/.choosenim/toolchains/nim-0.20.0/lib/system/mmdisp.nim
/home/djazz/.choosenim/toolchains/nim-0.20.0/lib/system/cellsets.nim
/home/djazz/.choosenim/toolchains/nim-0.20.0/lib/system.nim
/home/djazz/.choosenim/toolchains/nim-0.20.0/lib/system/strmantle.nim
/home/djazz/.choosenim/toolchains/nim-0.20.0/lib/system/fatal.nim
../../../../home/djazz/.choosenim/toolchains/nim-0.20.0/lib/system/fatal.nim
../../../../home/djazz/.choosenim/toolchains/nim-0.20.0/lib/system/gc.nim
```
Both -d:release and --listFullPaths:off:
```
../../../../home/djazz/.choosenim/toolchains/nim-0.20.0/lib/system/fatal.nim
```

**Comment by dizzyliam** [comment]
The problem here is on 210 of msgs.nim:
`result = if relPath.count("..") > 2: absPath else: relPath`
If the number of directories back the file is (relatively), is more than two, then it will compile with the full and absolute path. I personally, can't see a reason for this, so I'll make a pull request removing it.

**Comment by dizzyliam** [comment]
F-ed that one up because of a stupid mistake. My bad; trying again now...

**Comment by juancarlospaco** [comment]
Can `--opt:size` make those empty string :grey_question: 
Or any other flag to not even include the relative paths...

**Comment by dizzyliam** [comment]
That might be a good idea.

**Comment by SolitudeSF** [comment]
how is that a good idea? `--opt:size` has nothing to do with that. size of the binary is completely unrelated to leaking build paths.

**Comment by juancarlospaco** [comment]
I agree with @SolitudeSF 
But I dont see other flag, unless we change the existing ones, what about:

- `--listFullPaths:off` :arrow_right:  Empty string everywhere
- `--listFullPaths:relative` :arrow_right: Relative path everywhere
- `--listFullPaths:on`:arrow_right: Full path everywhere

**Comment by alaviss** [comment]
`--listFullPaths` is a switch for compiler messages. Previously #9766 accidentally make this switch affects codegen, which I've fixed in #11583.

The problem now only resides in how the compiler use these paths. Paths of modules outside the project being compiled used during codegen is always relative, but can leak easily with `../../home/<snip>/system.nim`.

A way to "fix" this is to apply `extractFilename()` on paths outside of the current project, or we do some magic to shorten them to `<project name>/module.nim`.

I think to remove all paths `--stacktrace:off` can be extended to do so (it's odd why that flag doesn't get rid of stack trace altogether).

**Comment by doongjohn** [comment]
I can still find full path in a binary file with `-d:release` `--excessiveStackTrace:off` is this intended? or am I missing something?

![](https://i.imgur.com/C62Ew01.png)

**Comment by alaviss** [comment]
It doesn't come from Nim, but from the miniz C source code:

https://github.com/h3rald/nim-miniz/blob/b47edf871f2c780b72dcce7da232ef5afee57d56/src/libminiz.c#L1907

You can compile with `--passC:-DNDEBUG` to disable assertions within miniz.

**Comment by maninwire** [comment]
I am testing this on nim 1.6.4 and win10, with different nim files and I am not getting the expected result. My command  is "nim c -d:release --passC:-DNDEBUG --listFullPaths:off --excessiveStackTrace:off --opt:size filename.nim ". With one single import of puppy I am getting 77 lines of nimble paths when testing with "strings", all leaking the local username.

**Comment by lewisl** [comment]
still a problem 5 years later...    ....and under admittedly rare circumstances it can completely break nim, the compiler.  I had installed 2.0.8 with choosenim (brilliant tool, by the way!).  It landed within my home directory, naturally.  At the time I called it firstnameLastname. For reasons of consistency between multiple machines, I changed the name of my home dir to firstname.  nim could not find components it needs and refused to run.   I then installed 2.0.6 to verify that yes, where you put it gets embedded--but now nim worked.  I then removed 2.0.8.  I re-installed 2.0.8 and verified that everything immediately was working.  I then removed 2.0.6.  All good. Not even that hard because the tool is reliable and requires no attention.

Now, it is not everyday that any nitwit (me) goes and changes the name of their homedir, but stranger things have happened. A more realistic scenario is that someone wants to move the whole stack (it's not that big once you delete the .tar) to somewhere seemingly sensible like var or usr/local/lib.  This entails only moving the directories choosenim and .nimble.  But, nim would break.  There has got to be some human readable, editable file that can hold the path to the nim executable.  

It might be undesirable to rely on some mystery text file adjacent to the nim binaries.  There could be a simple expedient that if the mystery file is there, nim looks at it and picks up the path, if valid.  If no file present or the path is invalid, nim keeps what it had in place.  Or there could be some --config command that effectively does the same thing in the rare-ish cases it is needed. 

Best of all would be eliminating the need for any such path embedded in any of the tools and relying instead on necessary files being in the same dir or in subdirs with invariant names.  The whole problem is that the full path from root on down is what gets embedded.  This would only be a requirement that needed components be in specific local dirs, of which the top level could be wherever the developer deemed it reasonable to put it.

**Comment by beef331** [comment]
@lewisl your problems are unrelated to this issue. This issue is that user data would leak into a binary for stack traces and the like. It's not related to Nim compiler paths.

**Comment by lewisl** [comment]
Fair enough.  That is worse especially for distributed code.

Both shouldn’t happen in such otherwise absolutely brilliant work.

From: Jason Beetham ***@***.***>
Reply-To: nim-lang/Nim ***@***.***>
Date: Monday, August 26, 2024 at 9:34 PM
To: nim-lang/Nim ***@***.***>
Cc: Lewis Levin ***@***.***>, Mention ***@***.***>
Subject: Re: [nim-lang/Nim] Compiled binary includes full path to internal nim files (#11572)


@lewisl<https://github.com/lewisl> your problems are unrelated to this issue. This issue is that user data would leak into a binary for stack traces and the like. Not related Nim compiler paths.
