### ISSUE TITLE
Compiler assertion

### ISSUE THREAD

**Issue by pmetras** [nim-lang/Nim#14562]
Compilation aborts with compiler assertion `not (son == nil)`.

### Example

Sorry, I can't produce an example demonstrating the error. Here is the stack trace with the debugging compiler: 
```
/home/.../nim-#devel/compiler/nim.nim(117) nim
/home/.../nim-#devel/compiler/nim.nim(82) handleCmdLine
/home/.../nim-#devel/compiler/cmdlinehelper.nim(92) loadConfigsAndRunMainCommand
/home/.../nim-#devel/compiler/main.nim(204) mainCommand
/home/.../nim-#devel/compiler/main.nim(101) commandCompileToC
/home/.../nim-#devel/compiler/modules.nim(143) compileProject
/home/.../nim-#devel/compiler/modules.nim(84) compileModule
/home/.../nim-#devel/compiler/passes.nim(210) processModule
/home/.../nim-#devel/compiler/passes.nim(86) processTopLevelStmt
/home/.../nim-#devel/compiler/sem.nim(602) myProcess
/home/.../nim-#devel/compiler/sem.nim(570) semStmtAndGenerateGenerics
/home/.../nim-#devel/compiler/semstmts.nim(2308) semStmt
/home/.../nim-#devel/compiler/semexprs.nim(1014) semExprNoType
/home/.../nim-#devel/compiler/semexprs.nim(2776) semExpr
/home/.../nim-#devel/compiler/semstmts.nim(2248) semStmtList
/home/.../nim-#devel/compiler/semexprs.nim(2673) semExpr
/home/.../nim-#devel/compiler/semexprs.nim(996) semDirectOp
/home/.../nim-#devel/compiler/semexprs.nim(889) afterCallActions
/home/.../nim-#devel/compiler/semexprs.nim(37) semTemplateExpr
/home/.../nim-#devel/compiler/sem.nim(408) semAfterMacroCall
/home/.../nim-#devel/compiler/semstmts.nim(2308) semStmt
/home/.../nim-#devel/compiler/semexprs.nim(1014) semExprNoType
/home/.../nim-#devel/compiler/semexprs.nim(2776) semExpr
/home/.../nim-#devel/compiler/semstmts.nim(2248) semStmtList
/home/.../nim-#devel/compiler/semexprs.nim(2775) semExpr
/home/.../nim-#devel/compiler/semexprs.nim(2487) semBlock
/home/.../nim-#devel/compiler/semexprs.nim(2776) semExpr
/home/.../nim-#devel/compiler/semstmts.nim(2248) semStmtList
/home/.../nim-#devel/compiler/semexprs.nim(2784) semExpr
/home/.../nim-#devel/compiler/semstmts.nim(207) semTry
/home/.../nim-#devel/compiler/semstmts.nim(111) semExprBranchScope
/home/.../nim-#devel/compiler/semstmts.nim(104) semExprBranch
/home/.../nim-#devel/compiler/semexprs.nim(2776) semExpr
/home/.../nim-#devel/compiler/semstmts.nim(2248) semStmtList
/home/.../nim-#devel/compiler/semexprs.nim(2776) semExpr
/home/.../nim-#devel/compiler/semstmts.nim(2248) semStmtList
/home/.../nim-#devel/compiler/semexprs.nim(2673) semExpr
/home/.../nim-#devel/compiler/semexprs.nim(996) semDirectOp
/home/.../nim-#devel/compiler/semexprs.nim(889) afterCallActions
/home/.../nim-#devel/compiler/semexprs.nim(37) semTemplateExpr
/home/.../nim-#devel/compiler/sem.nim(408) semAfterMacroCall
/home/.../nim-#devel/compiler/semstmts.nim(2308) semStmt
/home/.../nim-#devel/compiler/semexprs.nim(1014) semExprNoType
/home/.../nim-#devel/compiler/semexprs.nim(2776) semExpr
/home/.../nim-#devel/compiler/semstmts.nim(2248) semStmtList
/home/.../nim-#devel/compiler/semexprs.nim(2754) semExpr
/home/.../nim-#devel/compiler/semstmts.nim(164) semIf
/home/.../nim-#devel/compiler/semstmts.nim(104) semExprBranch
/home/.../nim-#devel/compiler/semexprs.nim(2776) semExpr
/home/.../nim-#devel/compiler/semstmts.nim(2248) semStmtList
/home/.../nim-#devel/compiler/semexprs.nim(2784) semExpr
/home/.../nim-#devel/compiler/semstmts.nim(207) semTry
/home/.../nim-#devel/compiler/semstmts.nim(111) semExprBranchScope
/home/.../nim-#devel/compiler/semstmts.nim(104) semExprBranch
/home/.../nim-#devel/compiler/semexprs.nim(2776) semExpr
/home/.../nim-#devel/compiler/semstmts.nim(2248) semStmtList
/home/.../nim-#devel/compiler/semexprs.nim(2776) semExpr
/home/.../nim-#devel/compiler/semstmts.nim(2248) semStmtList
/home/.../nim-#devel/compiler/semexprs.nim(2673) semExpr
/home/.../nim-#devel/compiler/semexprs.nim(996) semDirectOp
/home/.../nim-#devel/compiler/semexprs.nim(888) afterCallActions
/home/.../nim-#devel/compiler/sem.nim(476) semMacroExpr
/home/.../nim-#devel/compiler/sem.nim(419) semAfterMacroCall
/home/.../nim-#devel/compiler/semexprs.nim(2776) semExpr
/home/.../nim-#devel/compiler/semstmts.nim(2248) semStmtList
/home/.../nim-#devel/compiler/semexprs.nim(2775) semExpr
/home/.../nim-#devel/compiler/semexprs.nim(2487) semBlock
/home/.../nim-#devel/compiler/semexprs.nim(2776) semExpr
/home/.../nim-#devel/compiler/semstmts.nim(2248) semStmtList
/home/.../nim-#devel/compiler/semexprs.nim(2776) semExpr
/home/.../nim-#devel/compiler/semstmts.nim(2248) semStmtList
/home/.../nim-#devel/compiler/semexprs.nim(2775) semExpr
/home/.../nim-#devel/compiler/semexprs.nim(2487) semBlock
/home/.../nim-#devel/compiler/semexprs.nim(2776) semExpr
/home/.../nim-#devel/compiler/semstmts.nim(2248) semStmtList
/home/.../nim-#devel/compiler/semexprs.nim(2776) semExpr
/home/.../nim-#devel/compiler/semstmts.nim(2248) semStmtList
/home/.../nim-#devel/compiler/semexprs.nim(2673) semExpr
/home/.../nim-#devel/compiler/semexprs.nim(995) semDirectOp
/home/.../nim-#devel/compiler/semexprs.nim(844) semOverloadedCallAnalyseEffects
/home/.../nim-#devel/compiler/semcall.nim(554) semOverloadedCall
/home/.../nim-#devel/compiler/semcall.nim(357) resolveOverloads
/home/.../nim-#devel/compiler/semcall.nim(95) pickBestCandidate
/home/.../nim-#devel/compiler/sigmatch.nim(2529) matches
/home/.../nim-#devel/compiler/sigmatch.nim(2466) matchesAux
/home/.../nim-#devel/compiler/sigmatch.nim(2268) prepareOperand
/home/.../nim-#devel/compiler/semexprs.nim(52) semOperand
/home/.../nim-#devel/compiler/semexprs.nim(2687) semExpr
/home/.../nim-#devel/compiler/semexprs.nim(2279) semMagic
/home/.../nim-#devel/compiler/semexprs.nim(995) semDirectOp
/home/.../nim-#devel/compiler/semexprs.nim(844) semOverloadedCallAnalyseEffects
/home/.../nim-#devel/compiler/semcall.nim(554) semOverloadedCall
/home/.../nim-#devel/compiler/semcall.nim(357) resolveOverloads
/home/.../nim-#devel/compiler/semcall.nim(95) pickBestCandidate
/home/.../nim-#devel/compiler/sigmatch.nim(2529) matches
/home/.../nim-#devel/compiler/sigmatch.nim(2466) matchesAux
/home/.../nim-#devel/compiler/sigmatch.nim(2268) prepareOperand
/home/.../nim-#devel/compiler/semexprs.nim(52) semOperand
/home/.../nim-#devel/compiler/semexprs.nim(2700) semExpr
/home/.../nim-#devel/compiler/semexprs.nim(978) semIndirectOp
/home/.../nim-#devel/compiler/semexprs.nim(844) semOverloadedCallAnalyseEffects
/home/.../nim-#devel/compiler/semcall.nim(562) semOverloadedCall
/home/.../nim-#devel/compiler/semcall.nim(530) semResolvedCall
/home/.../nim-#devel/compiler/ast.nim(1095) add
/home/.../nim-#devel/lib/system/assertions.nim(29) failedAssertImpl
/home/.../nim-#devel/lib/system/assertions.nim(22) raiseAssert
/home/.../nim-#devel/lib/system/fatal.nim(49) sysFatal
Error: unhandled exception: /home/.../nim-#devel/compiler/ast.nim(1095, 10) `
not (son == nil)`  [AssertionDefect]

```

### Expected output

Should compile or produce an error message.

### Additional Information

```
$ ~/.choosenim/toolchains/nim-#devel/bin/nim_temp -v
Nim Compiler Version 1.3.3 [Linux: amd64]
Compiled at 2020-06-04
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches:
```

**Comment by pmetras** [comment]
I was able to craft an example from my code. The assertion does not appear with the compiler `nim c` any more but is still present with `nim check`.

### Example

```nim
type
  Roud[N: static uint] = object

template foo*[N: static uint](s: string): Roud[N] =
  "Hello!"

discard foo[30]("Yahoo!")
```

### Output

```sh
$ nim c -r tutu
Hint: used config file '/home/.../nim-#devel/config/nim.cfg' [Conf]
Hint: used config file '/home/.../nim-#devel/config/config.nims' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: tutu [Processing]
/home/.../tutu.nim(7, 13) Error: type expected, but got: 30
$ nim check tutu
Hint: used config file '/home/.../nim-#devel/config/nim.cfg' [Conf]
Hint: used config file '/home/.../nim-#devel/config/config.nims' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: tutu [Processing]
/home/.../tutu.nim(7, 13) Error: type expected, but got: 30
fatal.nim(49)            sysFatal
Error: unhandled exception: ast.nim(1095, 10) `
not (son == nil)`  [AssertionDefect]
```

**Comment by timotheecour** [comment]
seems like a duplicate of case3 from https://github.com/nim-lang/Nim/issues/9040, and probably a few other issues too (https://github.com/nim-lang/Nim/labels/Static%5BT%5D?page=2&q=is%3Aopen+label%3AStatic%5BT%5D).

**Comment by timotheecour** [comment]
@araq I'm still getting the same error after this patch; however, it is a duplicate of case3 from https://github.com/nim-lang/Nim/issues/9040 so it can stay closed (but closed as duplicate, not as fixed)

**Comment by Araq** [comment]
@timotheecour This bug was only about nimsuggest / "nim check" and the crash was fixed. The other bugs are about the wrong behaviour so I closed this one.

**Comment by pmetras** [comment]
@Araq, the initial bug was for a compiler crash when using `nim c` in my project. It also appeared with `nim check`. I tried to create a smaller example but the crash disappeared with `nim c` and was still present with `nim check`. So `nim c` and `nim check` have different behaviours in the example while they behave the same in my project.

Now, using
```
$ nim -v
Nim Compiler Version 1.3.5 [Linux: amd64]
Compiled at 2020-06-08
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 30c09e460778099633db084532672970954bb328
active boot switches: -d:release
```
I get `Error: illformed AST: ` instead of crashing the compiler...

You can keep this issue closed as @timotheecour's one #9040 covers more cases.

**Comment by Araq** [comment]
> You can keep this issue closed as @timotheecour's one #9040 covers more cases.

That was what I tried to say, yes.
