### ISSUE TITLE
Cache issue with getTempDir

### ISSUE THREAD

**Issue by 89z** [nim-lang/Nim#16531]
I have a file `%APPDATA%\nim\config.nims`:

~~~nim
import os
task r, "compile to temp":
   setCommand("compile")
   switch("run")
   switch("outdir", getTempDir())
~~~

and a file `C:\March\a.nim`:

~~~nim
echo "March"
~~~

and a file `C:\April\a.nim`:

~~~nim
echo "April"
~~~

The issue is, if I run `C:\March\a.nim`, and then `C:\April\a.nim`, I get `March`
both times. Tested with Nim 1.4.2. As a workaround, I am just not using the `run`
switch anymore, and only using `compile` by itself.

**Comment by juancarlospaco** [comment]
Use `--out:uniquefilename` or use a subfolder ?. :confused:

**Comment by 89z** [comment]
@juancarlospaco the point is to replicate `go run`:

https://golang.org/cmd/go#hdr-Compile_and_run_Go_program

your suggestion doesnt do that. Sometimes I just want to run a program, and dont care about, or want to deal with any resultant file. That means Nim should have a way to either throw away the resultant file automatically, or put it into a temporary folder automatically. Currently Nim doesnt have any way to do either, not considering the issue here.

**Comment by juancarlospaco** [comment]
`nim r file.nim`.

**Comment by 89z** [comment]
@juancarlospaco not sure what youre getting at, but that command youve put was already was I was using when I posted this issue, and it doesnt work. If the filename is the same, but the folders are different, you get the same output regardless if the content or timestamps are different.

**Comment by juancarlospaco** [comment]
```console
$ mkdir 0
$ mkdir 1
$ echo "echo 0" > 0/file.nim
$ echo "echo 1" > 1/file.nim
$ nim r 0/file.nim
0

$ nim r 1/file.nim
1

$ nim r 0/file.nim
0

$ nim r 1/file.nim
1

$
```

Can not reproduce.

**Comment by 89z** [comment]
You cant reproduce, but you arent using the same method as the original post. As I have said repeatedly, the given path needs to be the same. Like this:

~~~
cd March
nim r a.nim
cd ..\April
nim r a.nim
~~~

I would appreciate you just stop commenting, if you just going to half heartedly address the issue. I spent considerable time troubleshooting this, so if you arent willing to put the same care into it, then youre just wasting my time.

**Comment by timotheecour** [comment]
@89z can you retry with latest devel now that https://github.com/nim-lang/Nim/pull/16349 was merged?

**Comment by 89z** [comment]
I dont know how to do that, it seems the last Nightly was 12 days ago:

https://github.com/nim-lang/nightlies/releases

**Comment by timotheecour** [comment]
https://nim-lang.github.io/Nim/intern.html#rebuilding-the-compiler

**Comment by 89z** [comment]
I will just wait for next release I guess

**Comment by Clyybber** [comment]
Closing for now, please comment if it's not fixed with the next release/nightly.

**Comment by 89z** [comment]
Just tested again with the Nightly build, issue remains

**Comment by Clyybber** [comment]
@89z Did you try https://github.com/nim-lang/nightlies/releases/tag/2021-01-03-devel-cf714c129f7dd598863d1cc588e685df2438c658 ?

**Comment by timotheecour** [comment]
@89z re-compiling nim is trivial, you don't need to wait for nightly builds; eg:
`nim c -d:release -o:bin/nim_temp2 compiler/nim`

**Comment by 89z** [comment]
I tried "Nightly build on 2021-01-03 for branch version-1-4", the one @Clyybber linked doesnt have any artifacts.

**Comment by 89z** [comment]
I tried "Nightly build on 2021-01-03 for branch version-1-4", the one @Clyybber linked doesnt have any artifacts. If I try @timotheecour command I get this:

~~~
C:\Nim-devel\compiler\dfa.nim(33, 19) Error: cannot open file: std/private/asciitables
~~~

**Comment by Clyybber** [comment]
Yeah, 1.4 doesn't have the fix, only devel has.

**Comment by timotheecour** [comment]
@89z I forgot to add --lib:lib in command (fixed now), please retry

**Comment by 89z** [comment]
Ok I think it worked, but I dont see any `nim.exe`, only `nim_temp2.exe`

**Comment by timotheecour** [comment]
> but I dont see any nim.exe, only nim_temp2.exe

you can specify where you want to generate the binary in the `-o:` flag

**Comment by 89z** [comment]
Just tested it again with the one I built, still doesnt work, still get March both times

**Comment by 89z** [comment]
Ok yes if I build it myself it works. But this command works fine:

~~~
nim c --lib:lib -d:release compiler/nim
~~~

not sure what problems you are talking about. Also the command I put should be
the first thing in this section:

https://nim-lang.github.io/Nim/intern.html#rebuilding-the-compiler

as most people arent going to want to mess with the deeper internals. Those extra
optional steps should be at the bottom.

**Comment by timotheecour** [comment]
> But this command works fine:

it affects commands that expect `compiler/nim` binary to be there (eg `./koch boot -d:release`) unlike the command i gave which can't corrupt `compiler/nim`

>> (it has to be under bin unless you know what you're doing)

> not sure what problems you are talking about

`nim c --lib:lib -d:release -o:otherdir/sub/nim compiler/nim` breaks `getPrefixDir` logic in compiler which expects the nim binary to be under `$nimroot/anydir` ie 1 level down from `$nimroot`


> Also the command I put should be the first thing in this section:

no for reasons given above to avoid corrupting `compiler/nim` when compiling nim from a repo in a buggy state. What would be ok would be to change internal logic to avoid depending on `compiler/nim.exe` and instead depending on say  `compiler/nim_bootstrap.exe`.

> Ok yes if I build it myself it works

so, can we close this?
