### ISSUE TITLE
Strange compilation error

### ISSUE THREAD

**Issue by markus-oberhumer** [nim-lang/Nim#6088]
The following program 

```
import tables                          # EITHER REMOVE THIS LINE

proc default[T](t: typedesc[T]): T {.noinline.} =
  result

static:
  doAssert default(string) == nil
  doAssert nil == default(string)       # OR REMOVE THIS LINE
```

gives a strange error message

```
$ nim c test.nim    
test.nim(8, 12) template/generic instantiation from here
lib/pure/collections/tables.nim(793, 12) Error: cannot instantiate: 'A'
```

For some reason it works if I remove the first or the last line.

Tested with nim 0.16.0 and current nim-git 0.17.1 03e0aa37e3d41c77475a2484e9a3d084e26bd8bf .

**Comment by bluenote10** [comment]
Simplified problem (results from the overloaded `==` for `OrderedTableRef[A, B])`):

```nimrod
import tables
doAssert nil == "asdf"
```

If you need a work-around you can use ``import tables except `==` ``

**Comment by markus-oberhumer** [comment]
This issue is not restricted to the `tables` module - actually is seems the compiler does have problems with all `ref object` types:

```
type
  Foo*[T] = ref object
    x: T

proc `==`*[T](a, b: Foo[T]): bool = 
  a.x == b.x

doAssert "abc" == nil            # compiles
doAssert nil == "abc"            # DOES NOT COMPILE
```

**Comment by Araq** [comment]
I see no bug here, type inference doesn't backtrack, the type parameter is resolved to ``nil`` when then later is marked as an invalid type. The error message could be better though.

**Comment by markus-oberhumer** [comment]
Hmm, maybe the compiler could at least give an error in case of ambiguity instead of trying to instantiate some (random?) version of `==`.

```
type
  X*[T] = ref object
    x: T
  Y*[T] = ref object
    y: T

proc `==`*[T](a, b: X[T]): bool = a.x == b.x
proc `==`*[T](a, b: Y[T]): bool = a.y == b.y

doAssert "abc" == nil            # compiles
doAssert nil == "abc"            # DOES NOT COMPILE
```

**Comment by markus-oberhumer** [comment]
And while I'm here this seems like a nice case for trying `not nil`.

This does not work:

```
type
  X*[T] = ref object
    x: T

proc `==`*[T](a, b: X[T] not nil): bool = a.x == b.x

doAssert "abc" == nil            # compiles
doAssert nil == "abc"            # DOES NOT COMPILE
```

But this does work:

```
type
  XX*[T] = object
    x: T
  X*[T] = ref XX[T] not nil

proc `==`*[T](a, b: X[T]): bool = a.x == b.x

doAssert "abc" == nil            # compiles
doAssert nil == "abc"            # compiles !
```

**Comment by andreaferretti** [comment]
I think type inference should take into account **all** type parameters

**Comment by krux02** [comment]
@markus-oberhumer since ``nil`` is not a default value anymore for string nor seq types, is the issue still relevant?

**Comment by bluenote10** [comment]
Since ref objects still exists, there's still some surprising behavior like:

```nim
# this compiles and runs fine
type RefObj = ref object
var x: RefObj
doAssert nil == x
```

```nim
# this doesn't compile
import tables
type RefObj = ref object
var x: RefObj
doAssert nil == x
```

The second example errors with `cannot instantiate: 'A'` and it is not clear what `A` is actually referring to.

Would the solution really require to backtrack the type inference or would it be possible to give `==(x: ref T, y: ref T)` (or so) the same precedence as the overload of `==` for table?

**Comment by markus-oberhumer** [comment]
The example from bluenote10 above https://github.com/nim-lang/Nim/issues/6088#issuecomment-437991556 now causes an internal compiler error with nim-1.6.12 ...

` internal error: getTypeDescAux(tyGenericParam)`

Closing this issue after more than 5 years.
