### ISSUE TITLE
nonpure enum can hijack pure enum; instead should give `Error: ambiguous identifier` ; pure and nonpure should both mean the same thing; pure should be deprecated

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8850]
now that https://github.com/nim-lang/Nim/commit/2f7b979e384ff6cc750e123939401a72c3f59093 was committed, I think we should do the following (see rationale below)
* P1: nonpure enum clashing with pure enum should give `Error: ambiguous identifier` ; see example below
* P2: pure and nonpure should both mean the same thing
* P3: pure should be deprecated (would become a noop under this proposal)

see https://github.com/nim-lang/Nim/issues/8066 for related discussion

```nim
when defined(case5):
  import typetraits
  type
    X {.pure.} = enum
      blue
      red
      magenta

    Y = enum
      blue
      orange
      red

  echo int(red) # prints 2 (not 1, nonpure takes over currently) but should give ambiguity error as in https://github.com/nim-lang/Nim/commit/2f7b979e384ff6cc750e123939401a72c3f59093
```

## rationale:
imagine following scenario:
```nim
# thirdpartylib1.nim:
type
    X {.pure.} = enum
      blue
      red
      magenta

# thirdpartylib2.nim:
# nothing yet

# myapp.nim:
import thirdpartylib1
import thirdpartylib2
call_c_library(int(red)) # call_c_library(1)
```

later thirdpartylib2.nim gets udpated as follows:
```nim
type
    Y = enum
      blue
      orange
      red
```
Now `call_c_library(int(red))` calls `call_c_library(2)`
this can lead to nasty bugs under the nose of application writer.
Instead the only sane way here is to give compile error: `Error: ambiguous identifier` (P1)

Which leads to P2 and P3 since now pure and impure would mean the same thing

## nit
impure allows UFCS: `int.red` , pure doesn't unless the symbol is qualified: `X.red.int` or `int(red)` ; if we are to do P2 and P3, I'm fine with either rule (allow or disallow UFCS without qualification (when unambigious))

**Comment by Araq** [comment]
> echo int(red) # prints 2 (not 1, nonpure takes over currently) but should give ambiguity error

No, it works as expected and documented. It's true that I want to merge pure and non-pure enums though, eventually.

**Comment by Araq** [comment]
> imagine following scenario...

These scenarios can always be conjectured and are not convincing. If they were, we wouldn't embrace overloading to begin with.

**Comment by PMunch** [comment]
That isn't a very obscure scenario though.. I'd imagine a lot of people using enums this way, and any module that happens to use the same value for an enum would break that.. I'm still for bringing pure enums back, can't really see a reason to remove them..

**Comment by Araq** [comment]
Once we merged pure with non-pure enums completely the scenario is gone. And yes, ``call_c_library(int(red))`` is a completely contrived example.

**Comment by timotheecour** [comment]
@araq confirmed on gitter https://gitter.im/nim-lang/Nim?at=5bafb1e019b139275a1de6ac that
nonpure enum will behave as current pure enum (after its meaning was modified in https://github.com/nim-lang/Nim/commit/2f7b979e384ff6cc750e123939401a72c3f59093), which allows both `Foo.red` and `red` wherever un-ambiguous), making {.pure.} both the new default and a no-op; this would therefore close this issue since "nonpure enum can hijack pure enum" won't happen after that.

(please correct me if I mis-understood)

**Comment by Araq** [comment]
I can confirm that's what will be done.

**Comment by timotheecour** [comment]
EDIT: i read somewhere (sorry, forgot whether it was in IRC or forum or github) that pure is now a no-op (ie implicit), however that's still not the case in latest devel (b2a5195e92f8852a47ca70136b103bc374b73393); pure and non pure still have different semantics
